/*
 * Copyright 2018 The Higgs Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.vilada.higgs.serialization.thrift.dto;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-10-16")
public class TWebAgentLoadBatch implements org.apache.thrift.TBase<TWebAgentLoadBatch, TWebAgentLoadBatch._Fields>, java.io.Serializable, Cloneable, Comparable<TWebAgentLoadBatch> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TWebAgentLoadBatch");

  private static final org.apache.thrift.protocol.TField LOAD_BATCH_FIELD_DESC = new org.apache.thrift.protocol.TField("loadBatch", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TWebAgentLoadBatchStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TWebAgentLoadBatchTupleSchemeFactory();

  public java.util.List<TWebAgentLoad> loadBatch; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOAD_BATCH((short)1, "loadBatch");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOAD_BATCH
          return LOAD_BATCH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOAD_BATCH, new org.apache.thrift.meta_data.FieldMetaData("loadBatch", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "TWebAgentLoad"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TWebAgentLoadBatch.class, metaDataMap);
  }

  public TWebAgentLoadBatch() {
  }

  public TWebAgentLoadBatch(
    java.util.List<TWebAgentLoad> loadBatch)
  {
    this();
    this.loadBatch = loadBatch;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TWebAgentLoadBatch(TWebAgentLoadBatch other) {
    if (other.isSetLoadBatch()) {
      java.util.List<TWebAgentLoad> __this__loadBatch = new java.util.ArrayList<TWebAgentLoad>(other.loadBatch.size());
      for (TWebAgentLoad other_element : other.loadBatch) {
        __this__loadBatch.add(other_element);
      }
      this.loadBatch = __this__loadBatch;
    }
  }

  public TWebAgentLoadBatch deepCopy() {
    return new TWebAgentLoadBatch(this);
  }


  public void clear() {
    this.loadBatch = null;
  }

  public int getLoadBatchSize() {
    return (this.loadBatch == null) ? 0 : this.loadBatch.size();
  }

  public java.util.Iterator<TWebAgentLoad> getLoadBatchIterator() {
    return (this.loadBatch == null) ? null : this.loadBatch.iterator();
  }

  public void addToLoadBatch(TWebAgentLoad elem) {
    if (this.loadBatch == null) {
      this.loadBatch = new java.util.ArrayList<TWebAgentLoad>();
    }
    this.loadBatch.add(elem);
  }

  public java.util.List<TWebAgentLoad> getLoadBatch() {
    return this.loadBatch;
  }

  public TWebAgentLoadBatch setLoadBatch(java.util.List<TWebAgentLoad> loadBatch) {
    this.loadBatch = loadBatch;
    return this;
  }

  public void unsetLoadBatch() {
    this.loadBatch = null;
  }

  /** Returns true if field loadBatch is set (has been assigned a value) and false otherwise */
  public boolean isSetLoadBatch() {
    return this.loadBatch != null;
  }

  public void setLoadBatchIsSet(boolean value) {
    if (!value) {
      this.loadBatch = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LOAD_BATCH:
      if (value == null) {
        unsetLoadBatch();
      } else {
        setLoadBatch((java.util.List<TWebAgentLoad>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LOAD_BATCH:
      return getLoadBatch();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LOAD_BATCH:
      return isSetLoadBatch();
    }
    throw new IllegalStateException();
  }


  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TWebAgentLoadBatch)
      return this.equals((TWebAgentLoadBatch)that);
    return false;
  }

  public boolean equals(TWebAgentLoadBatch that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_loadBatch = true && this.isSetLoadBatch();
    boolean that_present_loadBatch = true && that.isSetLoadBatch();
    if (this_present_loadBatch || that_present_loadBatch) {
      if (!(this_present_loadBatch && that_present_loadBatch))
        return false;
      if (!this.loadBatch.equals(that.loadBatch))
        return false;
    }

    return true;
  }


  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLoadBatch()) ? 131071 : 524287);
    if (isSetLoadBatch())
      hashCode = hashCode * 8191 + loadBatch.hashCode();

    return hashCode;
  }


  public int compareTo(TWebAgentLoadBatch other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLoadBatch()).compareTo(other.isSetLoadBatch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoadBatch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loadBatch, other.loadBatch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }


  public String toString() {
    StringBuilder sb = new StringBuilder("TWebAgentLoadBatch(");
    boolean first = true;

    sb.append("loadBatch:");
    if (this.loadBatch == null) {
      sb.append("null");
    } else {
      sb.append(this.loadBatch);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TWebAgentLoadBatchStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TWebAgentLoadBatchStandardScheme getScheme() {
      return new TWebAgentLoadBatchStandardScheme();
    }
  }

  private static class TWebAgentLoadBatchStandardScheme extends org.apache.thrift.scheme.StandardScheme<TWebAgentLoadBatch> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TWebAgentLoadBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOAD_BATCH
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.loadBatch = new java.util.ArrayList<TWebAgentLoad>(_list0.size);
                TWebAgentLoad _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new TWebAgentLoad();
                  _elem1.read(iprot);
                  struct.loadBatch.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setLoadBatchIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TWebAgentLoadBatch struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.loadBatch != null) {
        oprot.writeFieldBegin(LOAD_BATCH_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.loadBatch.size()));
          for (TWebAgentLoad _iter3 : struct.loadBatch)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TWebAgentLoadBatchTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TWebAgentLoadBatchTupleScheme getScheme() {
      return new TWebAgentLoadBatchTupleScheme();
    }
  }

  private static class TWebAgentLoadBatchTupleScheme extends org.apache.thrift.scheme.TupleScheme<TWebAgentLoadBatch> {


    public void write(org.apache.thrift.protocol.TProtocol prot, TWebAgentLoadBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLoadBatch()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLoadBatch()) {
        {
          oprot.writeI32(struct.loadBatch.size());
          for (TWebAgentLoad _iter4 : struct.loadBatch)
          {
            _iter4.write(oprot);
          }
        }
      }
    }


    public void read(org.apache.thrift.protocol.TProtocol prot, TWebAgentLoadBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.loadBatch = new java.util.ArrayList<TWebAgentLoad>(_list5.size);
          TWebAgentLoad _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new TWebAgentLoad();
            _elem6.read(iprot);
            struct.loadBatch.add(_elem6);
          }
        }
        struct.setLoadBatchIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

